"""Customer-compatible field names derived from the 2026-08-24 Kibana exports.

Only standards-backed HL7 v2.x fields and observed CCDA section aliases whose exact
labels appear verbatim in the customer export are included. Deprecated-but-observed
legacy field numbers (for example DG1-8 Diagnostic Related Group and PR1-11 Surgeon)
are retained because the customer's queries reference them directly. Elasticsearch
metadata, derived multifields, field numbers absent from the export, and Prism-internal
enrichment keys are intentionally excluded.
"""

from __future__ import annotations

CUSTOMER_HL7_EXPORT_SHA256 = "59ce5352d3d7722e552686adcb40a7f3383a13ba6c7e42bf6e60837153061744"
CUSTOMER_CCDA_EXPORT_SHA256 = "0f73432e65f03f3f64ac536383061d4ca552744e32403b8eadb7ab08f984bbfb"
CUSTOMER_HL7_EXPORT_FIELD_COUNT = 3513
CUSTOMER_CCDA_EXPORT_FIELD_COUNT = 33509

HL7_FIELD_CATALOG: dict[str, dict[int, tuple[str, str | None]]] = {
    "ACC": {
        1: ("ACC_1_Accident_Date-Time", None),
        2: ("ACC_2_Accident_Code", "CWE"),
        3: ("ACC_3_Accident_Location", None),
        4: ("ACC_4_Auto_Accident_State", "CWE"),
        5: ("ACC_5_Accident_Job_Related_Indicator", None),
        6: ("ACC_6_Accident_Death_Indicator", None),
        8: ("ACC_8_Accident_Description", None),
        9: ("ACC_9_Brought_In_By", None),
    },
    "AL1": {
        1: ("AL1_1_Set_ID_-_AL1", None),
        2: ("AL1_2_Allergen_Type_Code", "CWE"),
        3: ("AL1_3_Allergen_Code-Mnemonic-Description", "CWE"),
        4: ("AL1_4_Allergy_Severity_Code", "CWE"),
        5: ("AL1_5_Allergy_Reaction_Code", None),
        6: ("AL1_6_Identification_Date", None),
    },
    "DG1": {
        1: ("DG1_1_Set_ID_-_DG1", None),
        2: ("DG1_2_Diagnosis_Coding_Method", None),
        3: ("DG1_3_Diagnosis_Code_-_DG1", "CWE"),
        4: ("DG1_4_Diagnosis_Description", None),
        5: ("DG1_5_Diagnosis_Date-Time", None),
        6: ("DG1_6_Diagnosis_Type", None),
        8: ("DG1_8_Diagnostic_Related_Group", "CNE"),
        15: ("DG1_15_Diagnosis_Priority", None),
        16: ("DG1_16_Diagnosing_Clinician", "XCN"),
        17: ("DG1_17_Diagnosis_Classification", None),
        18: ("DG1_18_Confidential_Indicator", None),
        20: ("DG1_20_Diagnosis_Identifier", "EI"),
        21: ("DG1_21_Diagnosis_Action_Code", None),
        22: ("DG1_22_Parent_Diagnosis", "EI"),
        23: ("DG1_23_DRG_CCL_Value_Code", "CWE"),
        24: ("DG1_24_DRG_Grouping_Usage", None),
        25: ("DG1_25_DRG_Diagnosis_Determination_Status", None),
        26: ("DG1_26_Present_On_Admission_(POA)_Indicator", None),
    },
    "DRG": {
        1: ("DRG_1_Diagnostic_Related_Group", "CNE"),
        2: ("DRG_2_DRG_Assigned_Date-Time", None),
        6: ("DRG_6_Outlier_Days", None),
        8: ("DRG_8_DRG_Payor", None),
    },
    "EVN": {
        1: ("EVN_1_Event_Type_Code", None),
        2: ("EVN_2_Recorded_Date-Time", None),
        3: ("EVN_3_Date-Time_Planned_Event", None),
        4: ("EVN_4_Event_Reason_Code", None),
        5: ("EVN_5_Operator_ID", "XCN"),
        6: ("EVN_6_Event_Occurred", None),
        7: ("EVN_7_Event_Facility", "HD"),
    },
    "GT1": {
        1: ("GT1_1_Set_ID_-_GT1", None),
        2: ("GT1_2_Guarantor_Number", "CX"),
        3: ("GT1_3_Guarantor_Name", "XPN"),
        4: ("GT1_4_Guarantor_Spouse_Name", "XPN"),
        5: ("GT1_5_Guarantor_Address", "XAD"),
        6: ("GT1_6_Guarantor_Ph_Num_-_Home", "XTN"),
        7: ("GT1_7_Guarantor_Ph_Num_-_Business", "XTN"),
        8: ("GT1_8_Guarantor_Date-Time_Of_Birth", None),
        9: ("GT1_9_Guarantor_Administrative_Sex", None),
        10: ("GT1_10_Guarantor_Type", None),
        11: ("GT1_11_Guarantor_Relationship", "CWE"),
        12: ("GT1_12_Guarantor_SSN", None),
        13: ("GT1_13_Guarantor_Date_-_Begin", None),
        15: ("GT1_15_Guarantor_Priority", None),
        16: ("GT1_16_Guarantor_Employer_Name", "XPN"),
        17: ("GT1_17_Guarantor_Employer_Address", "XAD"),
        18: ("GT1_18_Guarantor_Employer_Phone_Number", "XTN"),
        19: ("GT1_19_Guarantor_Employee_ID_Number", "CX"),
        20: ("GT1_20_Guarantor_Employment_Status", None),
        21: ("GT1_21_Guarantor_Organization_Name", "XON"),
        23: ("GT1_23_Guarantor_Credit_Rating_Code", "CWE"),
        24: ("GT1_24_Guarantor_Death_Date_And_Time", None),
        25: ("GT1_25_Guarantor_Death_Flag", None),
        26: ("GT1_26_Guarantor_Charge_Adjustment_Code", "CWE"),
        27: ("GT1_27_Guarantor_Household_Annual_Income", "CP"),
        28: ("GT1_28_Guarantor_Household_Size", None),
        29: ("GT1_29_Guarantor_Employer_ID_Number", "CX"),
        30: ("GT1_30_Guarantor_Marital_Status_Code", "CWE"),
        31: ("GT1_31_Guarantor_Hire_Effective_Date", None),
        32: ("GT1_32_Employment_Stop_Date", None),
        36: ("GT1_36_Primary_Language", "CWE"),
        38: ("GT1_38_Publicity_Code", "CWE"),
        40: ("GT1_40_Student_Indicator", None),
        41: ("GT1_41_Religion", "CWE"),
        42: ("GT1_42_Mother's_Maiden_Name", "XPN"),
        43: ("GT1_43_Nationality", "CWE"),
        44: ("GT1_44_Ethnic_Group", "CWE"),
        45: ("GT1_45_Contact_Person's_Name", "XPN"),
        46: ("GT1_46_Contact_Person's_Telephone_Number", "XTN"),
        47: ("GT1_47_Contact_Reason", "CWE"),
        48: ("GT1_48_Contact_Relationship", None),
        49: ("GT1_49_Job_Title", None),
        51: ("GT1_51_Guarantor_Employer's_Organization_Name", "XON"),
        52: ("GT1_52_Handicap", None),
        53: ("GT1_53_Job_Status", None),
        54: ("GT1_54_Guarantor_Financial_Class", "FC"),
        55: ("GT1_55_Guarantor_Race", "CWE"),
        56: ("GT1_56_Guarantor_Birth_Place", None),
    },
    "IN1": {
        1: ("IN1_1_Set_ID_-_IN1", None),
        2: ("IN1_2_Insurance_Plan_ID", "CWE"),
        3: ("IN1_3_Insurance_Company_ID", "CX"),
        4: ("IN1_4_Insurance_Company_Name", "XON"),
        5: ("IN1_5_Insurance_Company_Address", "XAD"),
        6: ("IN1_6_Insurance_Co_Contact_Person", "XPN"),
        7: ("IN1_7_Insurance_Co_Phone_Number", "XTN"),
        8: ("IN1_8_Group_Number", None),
        9: ("IN1_9_Group_Name", "XON"),
        10: ("IN1_10_Insured's_Group_Emp_ID", "CX"),
        11: ("IN1_11_Insured's_Group_Emp_Name", "XON"),
        12: ("IN1_12_Plan_Effective_Date", None),
        13: ("IN1_13_Plan_Expiration_Date", None),
        14: ("IN1_14_Authorization_Information", "AUI"),
        15: ("IN1_15_Plan_Type", None),
        16: ("IN1_16_Name_Of_Insured", "XPN"),
        17: ("IN1_17_Insured's_Relationship_To_Patient", "CWE"),
        18: ("IN1_18_Insured's_Date_Of_Birth", None),
        19: ("IN1_19_Insured's_Address", "XAD"),
        20: ("IN1_20_Assignment_Of_Benefits", None),
        21: ("IN1_21_Coordination_Of_Benefits", None),
        22: ("IN1_22_Coord_Of_Ben_Priority", None),
        23: ("IN1_23_Notice_Of_Admission_Flag", None),
        25: ("IN1_25_Report_Of_Eligibility_Flag", None),
        26: ("IN1_26_Report_Of_Eligibility_Date", None),
        27: ("IN1_27_Release_Information_Code", None),
        28: ("IN1_28_Pre-Admit_Cert_(PAC)", None),
        29: ("IN1_29_Verification_Date-Time", None),
        30: ("IN1_30_Verification_By", "XCN"),
        31: ("IN1_31_Type_Of_Agreement_Code", None),
        32: ("IN1_32_Billing_Status", None),
        33: ("IN1_33_Lifetime_Reserve_Days", None),
        35: ("IN1_35_Company_Plan_Code", None),
        36: ("IN1_36_Policy_Number", None),
        37: ("IN1_37_Policy_Deductible", "CP"),
        38: ("IN1_38_Policy_Limit_-_Amount", None),
        39: ("IN1_39_Policy_Limit_-_Days", None),
        40: ("IN1_40_Room_Rate_-_Semi-Private", None),
        41: ("IN1_41_Room_Rate_-_Private", None),
        42: ("IN1_42_Insured's_Employment_Status", "CWE"),
        43: ("IN1_43_Insured's_Administrative_Sex", None),
        44: ("IN1_44_Insured's_Employer's_Address", "XAD"),
        45: ("IN1_45_Verification_Status", None),
        46: ("IN1_46_Prior_Insurance_Plan_ID", None),
        47: ("IN1_47_Coverage_Type", None),
        48: ("IN1_48_Handicap", None),
        49: ("IN1_49_Insured's_ID_Number", "CX"),
        50: ("IN1_50_Signature_Code", None),
    },
    "IN2": {
        1: ("IN2_1_Insured's_Employee_ID", "CX"),
        2: ("IN2_2_Insured's_Social_Security_Number", None),
        3: ("IN2_3_Insured's_Employer's_Name_and_ID", "XCN"),
        4: ("IN2_4_Employer_Information_Data", None),
        5: ("IN2_5_Mail_Claim_Party", None),
        6: ("IN2_6_Medicare_Health_Ins_Card_Number", None),
        7: ("IN2_7_Medicaid_Case_Name", "XPN"),
        8: ("IN2_8_Medicaid_Case_Number", None),
        9: ("IN2_9_Military_Sponsor_Name", "XPN"),
        10: ("IN2_10_Military_ID_Number", None),
        11: ("IN2_11_Dependent_Of_Military_Recipient", "CWE"),
        12: ("IN2_12_Military_Organization", None),
        13: ("IN2_13_Military_Station", None),
        14: ("IN2_14_Military_Service", None),
        15: ("IN2_15_Military_Rank-Grade", None),
        16: ("IN2_16_Military_Status", None),
        21: ("IN2_21_Blood_Deductible", None),
        25: ("IN2_25_Payor_ID", "CX"),
        26: ("IN2_26_Payor_Subscriber_ID", "CX"),
        30: ("IN2_30_Daily_Deductible", "DDI"),
        33: ("IN2_33_Citizenship", "CWE"),
        34: ("IN2_34_Primary_Language", "CWE"),
        36: ("IN2_36_Publicity_Code", "CWE"),
        39: ("IN2_39_Religion", "CWE"),
        40: ("IN2_40_Mother's_Maiden_Name", "XPN"),
        42: ("IN2_42_Ethnic_Group", "CWE"),
        43: ("IN2_43_Marital_Status", "CWE"),
        44: ("IN2_44_Insured's_Employment_Start_Date", None),
        46: ("IN2_46_Job_Title", None),
        49: ("IN2_49_Employer_Contact_Person_Name", "XPN"),
        50: ("IN2_50_Employer_Contact_Person_Phone_Number", "XTN"),
        61: ("IN2_61_Patient_Member_Number", "CX"),
        62: ("IN2_62_Guarantor's_Relationship_to_Insured", "CWE"),
        63: ("IN2_63_Insured's_Phone_Number_-_Home", "XTN"),
        64: ("IN2_64_Insured's_Employer_Phone_Number", "XTN"),
        65: ("IN2_65_Military_Handicapped_Program", "CWE"),
        66: ("IN2_66_Suspend_Flag", None),
        69: ("IN2_69_Insured_Organization_Name_and_ID", "XON"),
        70: ("IN2_70_Insured_Employer_Organization_Name_and_ID", "XON"),
        71: ("IN2_71_Race", "CWE"),
        72: ("IN2_72_Patient's_Relationship_to_Insured", "CWE"),
    },
    "IN3": {
        1: ("IN3_1_Set_ID_-_IN3", None),
        2: ("IN3_2_Certification_Number", "CX"),
        3: ("IN3_3_Certified_By", "XCN"),
        4: ("IN3_4_Certification_Required", None),
        6: ("IN3_6_Certification_Date-Time", None),
        7: ("IN3_7_Certification_Modify_Date-Time", None),
        8: ("IN3_8_Operator", "XCN"),
        9: ("IN3_9_Certification_Begin_Date", None),
        10: ("IN3_10_Certification_End_Date", None),
        11: ("IN3_11_Days", "DTN"),
        15: ("IN3_15_Certification_Contact", None),
        16: ("IN3_16_Certification_Contact_Phone_Number", "XTN"),
        17: ("IN3_17_Appeal_Reason", "CWE"),
    },
    "MRG": {
        1: ("MRG_1_Prior_Patient_Identifier_List", "CX"),
        3: ("MRG_3_Prior_Patient_Account_Number", "CX"),
        4: ("MRG_4_Prior_Patient_ID", "CX"),
        5: ("MRG_5_Prior_Visit_Number", "CX"),
        6: ("MRG_6_Prior_Alternate_Visit_ID", "CX"),
        7: ("MRG_7_Prior_Patient_Name", "XPN"),
    },
    "MSH": {
        1: ("MSH_1_Field_Separator", None),
        2: ("MSH_2_Encoding_Characters", None),
        3: ("MSH_3_Sending_Application", "HD"),
        4: ("MSH_4_Sending_Facility", "HD"),
        5: ("MSH_5_Receiving_Application", "HD"),
        6: ("MSH_6_Receiving_Facility", "HD"),
        7: ("MSH_7_Date-Time_of_Message", None),
        8: ("MSH_8_Security", None),
        9: ("MSH_9_Message_Type", "MSG"),
        10: ("MSH_10_Message_Control_ID", None),
        11: ("MSH_11_Processing_ID", "PT"),
        12: ("MSH_12_Version_ID", "VID"),
        13: ("MSH_13_Sequence_Number", None),
        14: ("MSH_14_Continuation_Pointer", None),
        15: ("MSH_15_Accept_Acknowledgment_Type", None),
        16: ("MSH_16_Application_Acknowledgment_Type", None),
        17: ("MSH_17_Country_Code", None),
        18: ("MSH_18_Character_Set", None),
        19: ("MSH_19_Principal_Language_Of_Message", "CWE"),
        20: ("MSH_20_Alternate_Character_Set_Handling_Scheme", None),
        21: ("MSH_21_Message_Profile_Identifier", "EI"),
    },
    "NK1": {
        1: ("NK1_1_Set_ID_-_NK1", None),
        2: ("NK1_2_Name", "XPN"),
        3: ("NK1_3_Relationship", "CWE"),
        4: ("NK1_4_Address", "XAD"),
        5: ("NK1_5_Phone_Number", "XTN"),
        6: ("NK1_6_Business_Phone_Number", "XTN"),
        7: ("NK1_7_Contact_Role", "CWE"),
        8: ("NK1_8_Start_Date", None),
        9: ("NK1_9_End_Date", None),
        10: ("NK1_10_Next_of_Kin_-_Associated_Parties_Job_Title", None),
        11: ("NK1_11_Next_of_Kin_-_Associated_Parties_Job_Code-Class", "JCC"),
        12: ("NK1_12_Next_of_Kin_-_Associated_Parties_Employee_Number", "CX"),
        13: ("NK1_13_Organization_Name_-_NK1", "XON"),
        14: ("NK1_14_Marital_Status", "CWE"),
        15: ("NK1_15_Administrative_Sex", None),
        16: ("NK1_16_Date-Time_of_Birth", None),
        17: ("NK1_17_Living_Dependency", None),
        20: ("NK1_20_Primary_Language", "CWE"),
        21: ("NK1_21_Living_Arrangement", None),
        23: ("NK1_23_Protection_Indicator", None),
        24: ("NK1_24_Student_Indicator", None),
        25: ("NK1_25_Religion", "CWE"),
        26: ("NK1_26_Mother's_Maiden_Name", "XPN"),
        27: ("NK1_27_Nationality", "CWE"),
        28: ("NK1_28_Ethnic_Group", "CWE"),
        29: ("NK1_29_Contact_Reason", "CWE"),
        30: ("NK1_30_Contact_Person's_Name", "XPN"),
        31: ("NK1_31_Contact_Person's_Telephone_Number", "XTN"),
        32: ("NK1_32_Contact_Person's_Address", "XAD"),
        33: ("NK1_33_Next_of_Kin-Associated_Party's_Identifiers", "CX"),
        34: ("NK1_34_Job_Status", None),
        35: ("NK1_35_Race", "CWE"),
        36: ("NK1_36_Handicap", None),
        37: ("NK1_37_Contact_Person_Social_Security_Number", None),
    },
    "NTE": {
        1: ("NTE_1_Set_ID_-_NTE", None),
        2: ("NTE_2_Source_of_Comment", None),
        3: ("NTE_3_Comment", None),
        4: ("NTE_4_Comment_Type", "CWE"),
        5: ("NTE_5_Entered_By", "XCN"),
    },
    "OBR": {
        1: ("OBR_1_Set_ID_-_OBR", None),
        2: ("OBR_2_Placer_Order_Number", "EI"),
        3: ("OBR_3_Filler_Order_Number", "EI"),
        4: ("OBR_4_Universal_Service_Identifier", "CWE"),
        5: ("OBR_5_Priority", None),
        6: ("OBR_6_Requested_Date-Time", None),
        7: ("OBR_7_Observation_Date-Time_#", None),
        8: ("OBR_8_Observation_End_Date-Time_#", None),
        9: ("OBR_9_Collection_Volume_*", "CQ"),
        10: ("OBR_10_Collector_Identifier_*", "XCN"),
        11: ("OBR_11_Specimen_Action_Code_*", None),
        12: ("OBR_12_Danger_Code", "CWE"),
        13: ("OBR_13_Relevant_Clinical_Information", None),
        14: ("OBR_14_Specimen_Received_Date-Time", None),
        15: ("OBR_15_Specimen_Source", "SPS"),
        16: ("OBR_16_Ordering_Provider", "XCN"),
        17: ("OBR_17_Order_Callback_Phone_Number", "XTN"),
        18: ("OBR_18_Placer_Field_1", None),
        19: ("OBR_19_Placer_Field_2", None),
        20: ("OBR_20_Filler_Field_1_", None),
        21: ("OBR_21_Filler_Field_2_", None),
        22: ("OBR_22_Results_Rpt-Status_Chng_-_Date-Time_", None),
        23: ("OBR_23_Charge_to_Practice_", "MOC"),
        24: ("OBR_24_Diagnostic_Serv_Sect_ID", None),
        25: ("OBR_25_Result_Status_", None),
        26: ("OBR_26_Parent_Result_", "PRL"),
        27: ("OBR_27_Quantity-Timing", "TQ"),
        28: ("OBR_28_Result_Copies_To", "XCN"),
        29: ("OBR_29_Parent", "EIP"),
        30: ("OBR_30_Transportation_Mode", None),
        31: ("OBR_31_Reason_for_Study", "CWE"),
        32: ("OBR_32_Principal_Result_Interpreter_", "NDL"),
        33: ("OBR_33_Assistant_Result_Interpreter_", "NDL"),
        34: ("OBR_34_Technician_", "NDL"),
        35: ("OBR_35_Transcriptionist_", "NDL"),
        36: ("OBR_36_Scheduled_Date-Time_", None),
        37: ("OBR_37_Number_of_Sample_Containers_*", None),
        38: ("OBR_38_Transport_Logistics_of_Collected_Sample_*", "CWE"),
        39: ("OBR_39_Collector's_Comment_*", "CWE"),
        40: ("OBR_40_Transport_Arrangement_Responsibility", "CWE"),
        44: ("OBR_44_Procedure_Code", "CNE"),
        45: ("OBR_45_Procedure_Code_Modifier", "CNE"),
        46: ("OBR_46_Placer_Supplemental_Service_Information", "CWE"),
        47: ("OBR_47_Filler_Supplemental_Service_Information", "CWE"),
    },
    "OBX": {
        1: ("OBX_1_Set_ID_-_OBX", None),
        2: ("OBX_2_Value_Type", None),
        3: ("OBX_3_Observation_Identifier", "CWE"),
        4: ("OBX_4_Observation_Sub-ID", None),
        5: ("OBX_5_Observation_Value", None),
        6: ("OBX_6_Units", "CWE"),
        7: ("OBX_7_References_Range", None),
        8: ("OBX_8_Abnormal_Flags", None),
        9: ("OBX_9_Probability", None),
        10: ("OBX_10_Nature_of_Abnormal_Test", None),
        11: ("OBX_11_Observation_Result_Status", None),
        12: ("OBX_12_Effective_Date_of_Reference_Range", None),
        13: ("OBX_13_User_Defined_Access_Checks", None),
        14: ("OBX_14_Date-Time_of_the_Observation", None),
        15: ("OBX_15_Producer's_ID", "CWE"),
        16: ("OBX_16_Responsible_Observer", "XCN"),
        17: ("OBX_17_Observation_Method", "CWE"),
        18: ("OBX_18_Equipment_Instance_Identifier", "EI"),
        19: ("OBX_19_Date-Time_of_the_Analysis", None),
        20: ("OBX_20_Observation_Site", "CWE"),
        21: ("OBX_21_Observation_Instance_Identifier", "EI"),
        22: ("OBX_22_Mood_Code", "CNE"),
        23: ("OBX_23_Performing_Organization_Name", "XON"),
        24: ("OBX_24_Performing_Organization_Address", "XAD"),
        25: ("OBX_25_Performing_Organization_Medical_Director", "XCN"),
    },
    "ORC": {
        1: ("ORC_1_Order_Control", None),
        2: ("ORC_2_Placer_Order_Number", "EI"),
        3: ("ORC_3_Filler_Order_Number", "EI"),
        4: ("ORC_4_Placer_Group_Number", "EI"),
        5: ("ORC_5_Order_Status", None),
        6: ("ORC_6_Response_Flag", None),
        7: ("ORC_7_Quantity-Timing", "TQ"),
        8: ("ORC_8_Parent", "EIP"),
        9: ("ORC_9_Date-Time_of_Transaction", None),
        10: ("ORC_10_Entered_By", "XCN"),
        11: ("ORC_11_Verified_By", "XCN"),
        12: ("ORC_12_Ordering_Provider", "XCN"),
        13: ("ORC_13_Enterer's_Location", "PL"),
        14: ("ORC_14_Call_Back_Phone_Number", "XTN"),
        15: ("ORC_15_Order_Effective_Date-Time", None),
        16: ("ORC_16_Order_Control_Code_Reason", "CWE"),
        17: ("ORC_17_Entering_Organization", "CWE"),
        18: ("ORC_18_Entering_Device", "CWE"),
        19: ("ORC_19_Action_By", "XCN"),
        20: ("ORC_20_Advanced_Beneficiary_Notice_Code", "CWE"),
        21: ("ORC_21_Ordering_Facility_Name", "XON"),
        22: ("ORC_22_Ordering_Facility_Address", "XAD"),
        23: ("ORC_23_Ordering_Facility_Phone_Number", "XTN"),
        24: ("ORC_24_Ordering_Provider_Address", "XAD"),
    },
    "PD1": {
        1: ("PD1_1_Living_Dependency", None),
        2: ("PD1_2_Living_Arrangement", None),
        3: ("PD1_3_Patient_Primary_Facility", "XON"),
        4: ("PD1_4_Patient_Primary_Care_Provider_Name_&_ID_No", "XCN"),
        5: ("PD1_5_Student_Indicator", None),
        6: ("PD1_6_Handicap", None),
        7: ("PD1_7_Living_Will_Code", None),
        8: ("PD1_8_Organ_Donor_Code", None),
        11: ("PD1_11_Publicity_Code", "CWE"),
        12: ("PD1_12_Protection_Indicator", None),
        13: ("PD1_13_Protection_Indicator_Effective_Date", None),
        14: ("PD1_14_Place_of_Worship", "XON"),
        15: ("PD1_15_Advance_Directive_Code", "CWE"),
        16: ("PD1_16_Immunization_Registry_Status", None),
        17: ("PD1_17_Immunization_Registry_Status_Effective_Date", None),
        18: ("PD1_18_Publicity_Code_Effective_Date", None),
    },
    "PDA": {1: ("PDA_1_Death_Cause_Code", "CWE"), 3: ("PDA_3_Death_Certified_Indicator", None)},
    "PID": {
        1: ("PID_1_Set_ID_-_PID", None),
        2: ("PID_2_Patient_ID", "CX"),
        3: ("PID_3_Patient_Identifier_List", "CX"),
        4: ("PID_4_Alternate_Patient_ID_-_PID", "CX"),
        5: ("PID_5_Patient_Name", "XPN"),
        6: ("PID_6_Mother's_Maiden_Name", "XPN"),
        7: ("PID_7_Date-Time_of_Birth", None),
        8: ("PID_8_Administrative_Sex", None),
        9: ("PID_9_Patient_Alias", "XPN"),
        10: ("PID_10_Race", "CWE"),
        11: ("PID_11_Patient_Address", "XAD"),
        12: ("PID_12_County_Code", None),
        13: ("PID_13_Phone_Number_-_Home", "XTN"),
        14: ("PID_14_Phone_Number_-_Business", "XTN"),
        15: ("PID_15_Primary_Language", "CWE"),
        16: ("PID_16_Marital_Status", "CWE"),
        17: ("PID_17_Religion", "CWE"),
        18: ("PID_18_Patient_Account_Number", "CX"),
        19: ("PID_19_SSN_Number_-_Patient", None),
        20: ("PID_20_Driver's_License_Number_-_Patient", "DLN"),
        21: ("PID_21_Mother's_Identifier", "CX"),
        22: ("PID_22_Ethnic_Group", "CWE"),
        23: ("PID_23_Birth_Place", None),
        24: ("PID_24_Multiple_Birth_Indicator", None),
        25: ("PID_25_Birth_Order", None),
        26: ("PID_26_Citizenship", "CWE"),
        27: ("PID_27_Veterans_Military_Status", "CWE"),
        28: ("PID_28_Nationality", "CWE"),
        29: ("PID_29_Patient_Death_Date_and_Time", None),
        30: ("PID_30_Patient_Death_Indicator", None),
        31: ("PID_31_Identity_Unknown_Indicator", None),
        32: ("PID_32_Identity_Reliability_Code", None),
        33: ("PID_33_Last_Update_Date-Time", None),
        34: ("PID_34_Last_Update_Facility", "HD"),
        35: ("PID_35_Species_Code", "CWE"),
        37: ("PID_37_Strain", None),
        38: ("PID_38_Production_Class_Code", "CWE"),
    },
    "PR1": {
        1: ("PR1_1_Set_ID_-_PR1", None),
        2: ("PR1_2_Procedure_Coding_Method", None),
        3: ("PR1_3_Procedure_Code", "CNE"),
        4: ("PR1_4_Procedure_Description", None),
        5: ("PR1_5_Procedure_Date-Time", None),
        6: ("PR1_6_Procedure_Functional_Type", None),
        7: ("PR1_7_Procedure_Minutes", None),
        8: ("PR1_8_Anesthesiologist", None),
        9: ("PR1_9_Anesthesia_Code", None),
        10: ("PR1_10_Anesthesia_Minutes", None),
        11: ("PR1_11_Surgeon", "XCN"),
        14: ("PR1_14_Procedure_Priority", None),
        15: ("PR1_15_Associated_Diagnosis_Code", "CWE"),
        16: ("PR1_16_Procedure_Code_Modifier", "CNE"),
        18: ("PR1_18_Tissue_Type_Code", "CWE"),
    },
    "PV1": {
        1: ("PV1_1_Set_ID_-_PV1", None),
        2: ("PV1_2_Patient_Class", None),
        3: ("PV1_3_Assigned_Patient_Location", "PL"),
        4: ("PV1_4_Admission_Type", None),
        5: ("PV1_5_Preadmit_Number", "CX"),
        6: ("PV1_6_Prior_Patient_Location", "PL"),
        7: ("PV1_7_Attending_Doctor", "XCN"),
        8: ("PV1_8_Referring_Doctor", "XCN"),
        9: ("PV1_9_Consulting_Doctor", "XCN"),
        10: ("PV1_10_Hospital_Service", None),
        11: ("PV1_11_Temporary_Location", "PL"),
        12: ("PV1_12_Preadmit_Test_Indicator", None),
        13: ("PV1_13_Re-admission_Indicator", None),
        14: ("PV1_14_Admit_Source", None),
        15: ("PV1_15_Ambulatory_Status", None),
        16: ("PV1_16_VIP_Indicator", None),
        17: ("PV1_17_Admitting_Doctor", "XCN"),
        18: ("PV1_18_Patient_Type", None),
        19: ("PV1_19_Visit_Number", "CX"),
        20: ("PV1_20_Financial_Class", "FC"),
        21: ("PV1_21_Charge_Price_Indicator", None),
        22: ("PV1_22_Courtesy_Code", None),
        24: ("PV1_24_Contract_Code", None),
        25: ("PV1_25_Contract_Effective_Date", None),
        26: ("PV1_26_Contract_Amount", None),
        29: ("PV1_29_Transfer_to_Bad_Debt_Code", None),
        30: ("PV1_30_Transfer_to_Bad_Debt_Date", None),
        31: ("PV1_31_Bad_Debt_Agency_Code", None),
        32: ("PV1_32_Bad_Debt_Transfer_Amount", None),
        33: ("PV1_33_Bad_Debt_Recovery_Amount", None),
        35: ("PV1_35_Delete_Account_Date", None),
        36: ("PV1_36_Discharge_Disposition", None),
        37: ("PV1_37_Discharged_to_Location", "DLD"),
        38: ("PV1_38_Diet_Type", "CWE"),
        39: ("PV1_39_Servicing_Facility", None),
        40: ("PV1_40_Bed_Status", None),
        41: ("PV1_41_Account_Status", None),
        42: ("PV1_42_Pending_Location", "PL"),
        43: ("PV1_43_Prior_Temporary_Location", "PL"),
        44: ("PV1_44_Admit_Date-Time", None),
        45: ("PV1_45_Discharge_Date-Time", None),
        46: ("PV1_46_Current_Patient_Balance", None),
        47: ("PV1_47_Total_Charges", None),
        48: ("PV1_48_Total_Adjustments", None),
        49: ("PV1_49_Total_Payments", None),
        50: ("PV1_50_Alternate_Visit_ID", "CX"),
        51: ("PV1_51_Visit_Indicator", None),
        52: ("PV1_52_Other_Healthcare_Provider", "XCN"),
    },
    "PV2": {
        1: ("PV2_1_Prior_Pending_Location", "PL"),
        2: ("PV2_2_Accommodation_Code", "CWE"),
        3: ("PV2_3_Admit_Reason", "CWE"),
        4: ("PV2_4_Transfer_Reason", "CWE"),
        5: ("PV2_5_Patient_Valuables", None),
        6: ("PV2_6_Patient_Valuables_Location", None),
        7: ("PV2_7_Visit_User_Code", None),
        8: ("PV2_8_Expected_Admit_Date-Time", None),
        9: ("PV2_9_Expected_Discharge_Date-Time", None),
        10: ("PV2_10_Estimated_Length_of_Inpatient_Stay", None),
        11: ("PV2_11_Actual_Length_of_Inpatient_Stay", None),
        12: ("PV2_12_Visit_Description", None),
        13: ("PV2_13_Referral_Source_Code", "XCN"),
        14: ("PV2_14_Previous_Service_Date", None),
        15: ("PV2_15_Employment_Illness_Related_Indicator", None),
        16: ("PV2_16_Purge_Status_Code", None),
        18: ("PV2_18_Special_Program_Code", None),
        19: ("PV2_19_Retention_Indicator", None),
        21: ("PV2_21_Visit_Publicity_Code", None),
        22: ("PV2_22_Visit_Protection_Indicator", None),
        23: ("PV2_23_Clinic_Organization_Name", "XON"),
        24: ("PV2_24_Patient_Status_Code", None),
        25: ("PV2_25_Visit_Priority_Code", None),
        26: ("PV2_26_Previous_Treatment_Date", None),
        27: ("PV2_27_Expected_Discharge_Disposition", None),
        29: ("PV2_29_First_Similar_Illness_Date", None),
        31: ("PV2_31_Recurring_Service_Code", None),
        32: ("PV2_32_Billing_Media_Code", None),
        34: ("PV2_34_Military_Partnership_Code", None),
        35: ("PV2_35_Military_Non-Availability_Code", None),
        36: ("PV2_36_Newborn_Baby_Indicator", None),
        37: ("PV2_37_Baby_Detained_Indicator", None),
        38: ("PV2_38_Mode_of_Arrival_Code", "CWE"),
        39: ("PV2_39_Recreational_Drug_Use_Code", "CWE"),
        40: ("PV2_40_Admission_Level_of_Care_Code", "CWE"),
        42: ("PV2_42_Patient_Condition_Code", "CWE"),
        43: ("PV2_43_Living_Will_Code", None),
        45: ("PV2_45_Advance_Directive_Code", "CWE"),
        47: ("PV2_47_Expected_LOA_Return_Date-Time", None),
    },
    "ROL": {
        1: ("ROL_1_Role_Instance_ID", "EI"),
        2: ("ROL_2_Action_Code", None),
        3: ("ROL_3_Role-ROL", "CWE"),
        4: ("ROL_4_Role_Person", "XCN"),
        5: ("ROL_5_Role_Begin_Date-Time", None),
        6: ("ROL_6_Role_End_Date-Time", None),
        8: ("ROL_8_Role_Action_Reason", "CWE"),
        9: ("ROL_9_Provider_Type", "CWE"),
        10: ("ROL_10_Organization_Unit_Type", "CWE"),
        11: ("ROL_11_Office-Home_Address-Birthplace", "XAD"),
        12: ("ROL_12_Phone", "XTN"),
    },
    "RXA": {
        1: ("RXA_1_Give_Sub-ID_Counter", None),
        2: ("RXA_2_Administration_Sub-ID_Counter", None),
        3: ("RXA_3_Date-Time_Start_of_Administration", None),
        4: ("RXA_4_Date-Time_End_of_Administration", None),
        5: ("RXA_5_Administered_Code", "CWE"),
        6: ("RXA_6_Administered_Amount", None),
        7: ("RXA_7_Administered_Units", "CWE"),
        9: ("RXA_9_Administration_Notes", "CWE"),
        10: ("RXA_10_Administering_Provider", "XCN"),
        11: ("RXA_11_Administered-at_Location", "LA2"),
        13: ("RXA_13_Administered_Strength", None),
        15: ("RXA_15_Substance_Lot_Number", None),
        16: ("RXA_16_Substance_Expiration_Date", None),
        17: ("RXA_17_Substance_Manufacturer_Name", "CWE"),
        18: ("RXA_18_Substance-Treatment_Refusal_Reason", "CWE"),
        20: ("RXA_20_Completion_Status", None),
        21: ("RXA_21_Action_Code_-_RXA", None),
        22: ("RXA_22_System_Entry_Date-Time", None),
    },
    "RXC": {
        1: ("RXC_1_RX_Component_Type", None),
        2: ("RXC_2_Component_Code", "CWE"),
        3: ("RXC_3_Component_Amount", None),
        4: ("RXC_4_Component_Units", "CWE"),
        5: ("RXC_5_Component_Strength", None),
        6: ("RXC_6_Component_Strength_Units", "CWE"),
        7: ("RXC_7_Supplementary_Code", "CWE"),
    },
    "RXE": {
        1: ("RXE_1_Quantity-Timing", "TQ"),
        2: ("RXE_2_Give_Code", "CWE"),
        3: ("RXE_3_Give_Amount_-_Minimum", None),
        4: ("RXE_4_Give_Amount_-_Maximum", None),
        5: ("RXE_5_Give_Units", "CWE"),
        6: ("RXE_6_Give_Dosage_Form", "CWE"),
        7: ("RXE_7_Provider's_Administration_Instructions", "CWE"),
        8: ("RXE_8_Deliver-To_Location", "LA1"),
        9: ("RXE_9_Substitution_Status", None),
        10: ("RXE_10_Dispense_Amount", None),
        11: ("RXE_11_Dispense_Units", "CWE"),
        12: ("RXE_12_Number_Of_Refills", None),
        13: ("RXE_13_Ordering_Provider's_DEA_Number", "XCN"),
        14: ("RXE_14_Pharmacist-Treatment_Supplier's_Verifier_ID", "XCN"),
        15: ("RXE_15_Prescription_Number", None),
        16: ("RXE_16_Number_of_Refills_Remaining", None),
        17: ("RXE_17_Number_of_Refills-Doses_Dispensed", None),
        19: ("RXE_19_Total_Daily_Dose", "CQ"),
        20: ("RXE_20_Needs_Human_Review", None),
        21: ("RXE_21_Pharmacy-Treatment_Supplier's_Special_Dispensing_Instructions", "CWE"),
        22: ("RXE_22_Give_Per_(Time_Unit)", None),
        23: ("RXE_23_Give_Rate_Amount", None),
        24: ("RXE_24_Give_Rate_Units", "CWE"),
        25: ("RXE_25_Give_Strength", None),
        26: ("RXE_26_Give_Strength_Units", "CWE"),
        27: ("RXE_27_Give_Indication", "CWE"),
        28: ("RXE_28_Dispense_Package_Size", None),
        29: ("RXE_29_Dispense_Package_Size_Unit", "CWE"),
        30: ("RXE_30_Dispense_Package_Method", None),
        31: ("RXE_31_Supplementary_Code", "CWE"),
        34: ("RXE_34_Give_Drug_Strength_Volume_Units", "CWE"),
        35: ("RXE_35_Controlled_Substance_Schedule", "CWE"),
        36: ("RXE_36_Formulary_Status", None),
        37: ("RXE_37_Pharmaceutical_Substance_Alternative", "CWE"),
    },
    "RXR": {
        1: ("RXR_1_Route", "CWE"),
        2: ("RXR_2_Administration_Site", "CWE"),
        4: ("RXR_4_Administration_Method", "CWE"),
        5: ("RXR_5_Routing_Instruction", "CWE"),
    },
    "SPM": {
        1: ("SPM_1_Set_ID_-_SPM", None),
        2: ("SPM_2_Specimen_ID", "EIP"),
        3: ("SPM_3_Specimen_Parent_IDs", "EIP"),
        4: ("SPM_4_Specimen_Type", "CWE"),
        7: ("SPM_7_Specimen_Collection_Method", "CWE"),
        8: ("SPM_8_Specimen_Source_Site", "CWE"),
        12: ("SPM_12_Specimen_Collection_Amount", "CQ"),
        14: ("SPM_14_Specimen_Description", None),
        17: ("SPM_17_Specimen_Collection_Date-Time", "DR"),
        18: ("SPM_18_Specimen_Received_Date-Time", None),
        26: ("SPM_26_Number_of_Specimen_Containers", None),
        27: ("SPM_27_Container_Type", "CWE"),
    },
    "TXA": {
        1: ("TXA_1_Set_ID-_TXA", None),
        2: ("TXA_2_Document_Type", None),
        3: ("TXA_3_Document_Content_Presentation", None),
        4: ("TXA_4_Activity_Date-Time", None),
        5: ("TXA_5_Primary_Activity_Provider_Code-Name", "XCN"),
        6: ("TXA_6_Origination_Date-Time", None),
        7: ("TXA_7_Transcription_Date-Time", None),
        8: ("TXA_8_Edit_Date-Time", None),
        9: ("TXA_9_Originator_Code-Name", "XCN"),
        10: ("TXA_10_Assigned_Document_Authenticator", "XCN"),
        11: ("TXA_11_Transcriptionist_Code-Name", "XCN"),
        12: ("TXA_12_Unique_Document_Number", "EI"),
        13: ("TXA_13_Parent_Document_Number", "EI"),
        14: ("TXA_14_Placer_Order_Number", "EI"),
        15: ("TXA_15_Filler_Order_Number", "EI"),
        16: ("TXA_16_Unique_Document_File_Name", None),
        17: ("TXA_17_Document_Completion_Status", None),
        18: ("TXA_18_Document_Confidentiality_Status", None),
        19: ("TXA_19_Document_Availability_Status", None),
        20: ("TXA_20_Document_Storage_Status", None),
        21: ("TXA_21_Document_Change_Reason", None),
        22: ("TXA_22_Authentication_Person,_Time_Stamp_(set)", "PPN"),
        23: ("TXA_23_Distributed_Copies_(Code_and_Name_of_Recipient(s)_)", "XCN"),
    },
    "UB2": {
        1: ("UB2_1_Set_ID_-_UB2", None),
        3: ("UB2_3_Condition_Code_(24-30)", None),
        6: ("UB2_6_Value_Amount_&_Code", "UVC"),
        7: ("UB2_7_Occurrence_Code_&_Date_(32-35)", "OCD"),
        8: ("UB2_8_Occurrence_Span_Code-Dates_(36)", "OSP"),
    },
}

HL7_DATATYPE_CATALOG: dict[str, tuple[tuple[str, str | None], ...]] = {
    "AD": (
        ("AD_1", None),
        ("AD_2", None),
        ("AD_3", None),
        ("AD_4", None),
        ("AD_5", None),
        ("AD_6", None),
        ("AD_7", None),
        ("AD_8", None),
    ),
    "AUI": (("AUI_1", None), ("AUI_2", None), ("AUI_3", None)),
    "CNE": (
        ("CNE_1", None),
        ("CNE_2", None),
        ("CNE_3", None),
        ("CNE_4", None),
        ("CNE_5", None),
        ("CNE_6", None),
        ("CNE_7", None),
        ("CNE_8", None),
        ("CNE_9", None),
    ),
    "CNN": (
        ("CNN_1", None),
        ("CNN_2", None),
        ("CNN_3", None),
        ("CNN_4", None),
        ("CNN_5", None),
        ("CNN_6", None),
        ("CNN_7", None),
        ("CNN_8", None),
        ("CNN_9", None),
        ("CNN_10", None),
        ("CNN_11", None),
    ),
    "CP": (
        ("CP_1", "MO"),
        ("CP_2", None),
        ("CP_3", None),
        ("CP_4", None),
        ("CP_5", "CWE"),
        ("CP_6", None),
    ),
    "CQ": (("CQ_1", None), ("CQ_2", "CWE")),
    "CQ_SIMPLE": (("CQ_SIMPLE_1", None), ("CQ_SIMPLE_2", None)),
    "CWE": (
        ("CWE_1", None),
        ("CWE_2", None),
        ("CWE_3", None),
        ("CWE_4", None),
        ("CWE_5", None),
        ("CWE_6", None),
        ("CWE_7", None),
        ("CWE_8", None),
        ("CWE_9", None),
    ),
    "CX": (
        ("CX_1", None),
        ("CX_2", None),
        ("CX_3", None),
        ("CX_4", "HD"),
        ("CX_5", None),
        ("CX_6", "HD"),
        ("CX_7", None),
        ("CX_8", None),
        ("CX_9", "CWE"),
        ("CX_10", "CWE"),
    ),
    "DDI": (("DDI_1", None), ("DDI_2", "MO"), ("DDI_3", None)),
    "DLD": (("DLD_1", "CWE"), ("DLD_2", None)),
    "DLN": (("DLN_1", None), ("DLN_2", None), ("DLN_3", None)),
    "DR": (("DR_1", None), ("DR_2", None)),
    "DTN": (("DTN_1", None), ("DTN_2", None)),
    "EI": (("EI_1", None), ("EI_2", None), ("EI_3", None), ("EI_4", None)),
    "EIP": (("EIP_1", "EI"), ("EIP_2", "EI")),
    "FC": (("FC_1", None), ("FC_2", None)),
    "FN": (("FN_1", None), ("FN_2", None), ("FN_3", None), ("FN_4", None), ("FN_5", None)),
    "HD": (("HD_1", None), ("HD_2", None), ("HD_3", None)),
    "JCC": (("JCC_1", None), ("JCC_2", None), ("JCC_3", None)),
    "LA1": (
        ("LA1_1", None),
        ("LA1_2", None),
        ("LA1_3", None),
        ("LA1_4", "HD"),
        ("LA1_5", None),
        ("LA1_6", None),
        ("LA1_7", None),
        ("LA1_8", None),
        ("LA1_9", "AD"),
    ),
    "LA2": (
        ("LA2_1", None),
        ("LA2_2", None),
        ("LA2_3", None),
        ("LA2_4", "HD"),
        ("LA2_5", None),
        ("LA2_6", None),
        ("LA2_7", None),
        ("LA2_8", None),
        ("LA2_9", None),
        ("LA2_10", None),
        ("LA2_11", None),
        ("LA2_12", None),
        ("LA2_13", None),
        ("LA2_14", None),
        ("LA2_15", None),
        ("LA2_16", None),
    ),
    "MO": (("MO_1", None), ("MO_2", None)),
    "MOC": (("MOC_1", "MO"), ("MOC_2", "CWE")),
    "MSG": (("MSG_1", None), ("MSG_2", None), ("MSG_3", None)),
    "NDL": (
        ("NDL_1", "CNN"),
        ("NDL_2", None),
        ("NDL_3", None),
        ("NDL_4", None),
        ("NDL_5", None),
        ("NDL_6", None),
        ("NDL_7", "HD"),
        ("NDL_8", None),
        ("NDL_9", None),
        ("NDL_10", None),
        ("NDL_11", None),
    ),
    "OCD": (("OCD_1", "CNE"), ("OCD_2", None)),
    "OSD": (
        ("OSD_1", None),
        ("OSD_2", None),
        ("OSD_3", None),
        ("OSD_4", None),
        ("OSD_5", None),
        ("OSD_6", None),
        ("OSD_7", None),
        ("OSD_8", None),
        ("OSD_9", None),
        ("OSD_10", None),
        ("OSD_11", None),
    ),
    "OSP": (("OSP_1", "CNE"), ("OSP_2", None), ("OSP_3", None)),
    "PL": (
        ("PL_1", None),
        ("PL_2", None),
        ("PL_3", None),
        ("PL_4", "HD"),
        ("PL_5", None),
        ("PL_6", None),
        ("PL_7", None),
        ("PL_8", None),
        ("PL_9", None),
        ("PL_10", "EI"),
        ("PL_11", "HD"),
    ),
    "PPN": (
        ("PPN_1", None),
        ("PPN_2", "FN"),
        ("PPN_3", None),
        ("PPN_4", None),
        ("PPN_5", None),
        ("PPN_6", None),
        ("PPN_7", None),
        ("PPN_8", None),
        ("PPN_9", "HD"),
        ("PPN_10", None),
        ("PPN_11", None),
        ("PPN_12", None),
        ("PPN_13", None),
        ("PPN_14", "HD"),
        ("PPN_15", None),
        ("PPN_16", None),
        ("PPN_17", "CWE"),
        ("PPN_18", "DR"),
        ("PPN_19", None),
        ("PPN_20", None),
        ("PPN_21", None),
        ("PPN_22", None),
        ("PPN_23", "CWE"),
        ("PPN_24", "CWE"),
    ),
    "PRL": (("PRL_1", "CWE"), ("PRL_2", None), ("PRL_3", None)),
    "PT": (("PT_1", None), ("PT_2", None)),
    "RI": (("RI_1", None), ("RI_2", None)),
    "SAD": (("SAD_1", None), ("SAD_2", None), ("SAD_3", None)),
    "SPS": (
        ("SPS_1", "CWE"),
        ("SPS_2", "CWE"),
        ("SPS_3", None),
        ("SPS_4", "CWE"),
        ("SPS_5", "CWE"),
        ("SPS_6", "CWE"),
        ("SPS_7", "CWE"),
    ),
    "TQ": (
        ("TQ_1", "CQ_SIMPLE"),
        ("TQ_2", "RI"),
        ("TQ_3", None),
        ("TQ_4", None),
        ("TQ_5", None),
        ("TQ_6", None),
        ("TQ_7", None),
        ("TQ_8", None),
        ("TQ_9", None),
        ("TQ_10", "OSD"),
        ("TQ_11", "CWE"),
        ("TQ_12", None),
    ),
    "UVC": (("UVC_1", "CNE"), ("UVC_2", "MO")),
    "VID": (("VID_1", None), ("VID_2", "CWE"), ("VID_3", "CWE")),
    "XAD": (
        ("XAD_1", "SAD"),
        ("XAD_2", None),
        ("XAD_3", None),
        ("XAD_4", None),
        ("XAD_5", None),
        ("XAD_6", None),
        ("XAD_7", None),
        ("XAD_8", None),
        ("XAD_9", None),
        ("XAD_10", None),
        ("XAD_11", None),
        ("XAD_12", "DR"),
        ("XAD_13", None),
        ("XAD_14", None),
        ("XAD_15", "CWE"),
        ("XAD_16", None),
        ("XAD_17", None),
        ("XAD_18", None),
        ("XAD_19", None),
        ("XAD_20", None),
        ("XAD_21", None),
        ("XAD_22", "CWE"),
        ("XAD_23", "EI"),
    ),
    "XCN": (
        ("XCN_1", None),
        ("XCN_2", "FN"),
        ("XCN_3", None),
        ("XCN_4", None),
        ("XCN_5", None),
        ("XCN_6", None),
        ("XCN_7", None),
        ("XCN_8", None),
        ("XCN_9", "HD"),
        ("XCN_10", None),
        ("XCN_11", None),
        ("XCN_12", None),
        ("XCN_13", None),
        ("XCN_14", "HD"),
        ("XCN_15", None),
        ("XCN_16", "CWE"),
        ("XCN_17", "DR"),
        ("XCN_18", None),
        ("XCN_19", None),
        ("XCN_20", None),
        ("XCN_21", None),
        ("XCN_22", "CWE"),
        ("XCN_23", "CWE"),
    ),
    "XON": (
        ("XON_1", None),
        ("XON_2", None),
        ("XON_3", None),
        ("XON_4", None),
        ("XON_5", None),
        ("XON_6", "HD"),
        ("XON_7", None),
        ("XON_8", "HD"),
        ("XON_9", None),
        ("XON_10", None),
    ),
    "XPN": (
        ("XPN_1", "FN"),
        ("XPN_2", None),
        ("XPN_3", None),
        ("XPN_4", None),
        ("XPN_5", None),
        ("XPN_6", None),
        ("XPN_7", None),
        ("XPN_8", None),
        ("XPN_9", "CWE"),
        ("XPN_10", "DR"),
        ("XPN_11", None),
        ("XPN_12", None),
        ("XPN_13", None),
        ("XPN_14", None),
    ),
    "XTN": (
        ("XTN_2", None),
        ("XTN_3", None),
        ("XTN_4", None),
        ("XTN_5", None),
        ("XTN_6", None),
        ("XTN_7", None),
        ("XTN_8", None),
        ("XTN_9", None),
        ("XTN_10", None),
        ("XTN_11", None),
        ("XTN_12", None),
        ("XTN_13", None),
        ("XTN_14", None),
        ("XTN_15", "CWE"),
        ("XTN_16", "CWE"),
        ("XTN_17", "EI"),
        ("XTN_18", None),
    ),
}

CCDA_SECTION_TITLE_CATALOG: dict[str, str] = {
    "activeandrecentlyadministeredmedications": (
        "active-and-Recently-Administered-Medications-section"
    ),
    "activeproblems": "active-Problems-section",
    "additionalsourcecomments": "additional-Source-Comments-section",
    "administeredmedications": "administered-Medications-section",
    "admissiondiagnosis": "admissionDiagnosis-section",
    "advanceddirectives": "advancedDirectives-section",
    "advancedirectives": "advance-Directives-section",
    "allergies": "allergies-section",
    "allergiesandadversereactions": "allergies-and-Adverse-Reactions-section",
    "anasthesia": "anasthesia-section",
    "assesment": "assesment-section",
    "assesmentandplan": "assesmentAndPlan-section",
    "birthhistory": "birth-History-section",
    "careteam": "care-Team-section",
    "careteaminformation": "cARE-TEAM-INFORMATION-section",
    "careteams": "careTeams-section",
    "chiefcomplaint": "chiefComplaint-section",
    "chiefcomplaintandreasonforvisit": "chiefComplaintAndReasonForVisit-section",
    "consultationnote": "consultation-Note-section",
    "datadisclaimer": "data-Disclaimer-section",
    "diagnosticimagingreport": "diagnostic-Imaging-Report-section",
    "dialysishistory": "dialysis-History-section",
    "dialysisplanoftreatment": "dialysis-Plan-of-Treatment-section",
    "dischargesummarynote": "discharge-Summary-Note-section",
    "dischargesummarynotes": "dISCHARGE-SUMMARY-NOTES-section",
    "encounterdetails": "encounter-Details-section",
    "encounters": "encounters-section",
    "familyhistory": "familyHistory-section",
    "foreigntravel": "foreign-Travel-section",
    "functionalstatus": "functionalStatus-section",
    "futureappointments": "fUTURE-APPOINTMENTS-section",
    "generalstatus": "generalStatus-section",
    "goals": "goals-section",
    "growthchartinformation": "growth-Chart-Information-section",
    "healthconcerns": "healthConcerns-section",
    "healthstatusevaluationsandoutcomes": "healthStatusEvaluationsAndOutcomes-section",
    "historicaldialysisprocedures": "historical-Dialysis-Procedures-section",
    "historyandphysicalnote": "history-and-physical-note-section",
    "historyandphysicalnotes": "hISTORY-AND-PHYSICAL-NOTES-section",
    "historyofpastillness": "historyOfPastIllness-section",
    "historyofpresentillness": "historyOfPresentIllness-section",
    "homehealthvisitactionsandnarratives": "home-Health-Visit---Actions-and-Narratives-section",
    "homehealthvisitcareplan": "home-Health-Visit---Care-Plan-section",
    "hospicevisitcareplan": "hospice-Visit---Care-Plan-section",
    "hospitaladmissionmedications": "hospitalAdmissionMedications-section",
    "hospitalconsultations": "hospitalConsultations-section",
    "hospitalcourse": "hospitalCourse-section",
    "hospitaldischargediagnosis": "hospitalDischargeDiagnosis-section",
    "hospitaldischargeinstructions": "hospitalDischargeInstructions-section",
    "hospitaldischargemedications": "hospitalDischargeMedications-section",
    "hospitaldischargephysical": "hospitalDischargePhysical-section",
    "hospitaldischargestudiessummary": "hospitalDischargeStudiesSummary-section",
    "imagingnotes": "iMAGING-NOTES-section",
    "immunization": "immunization-section",
    "immunizations": "immunizations-section",
    "instructions": "instructions-section",
    "insurance": "insurance-section",
    "insuranceproviders": "insurance-Providers-section",
    "interventions": "interventions-section",
    "laboratoryreportnarrativenotes": "lABORATORY-REPORT-NARRATIVE-NOTES-section",
    "laboratorytests": "lABORATORY-TESTS-section",
    "lastfiledvitalsigns": "last-Filed-Vital-Signs-section",
    "medicalequipment": "medicalEquipment-section",
    "medicalgeneralhistory": "medicalGeneralHistory-section",
    "medications": "medications-section",
    "medicationsadministered": "medicationsAdministered-section",
    "mentalstatus": "mentalStatus-section",
    "notefromeisenhowerhealth": "note-from-Eisenhower-Health-section",
    "notes": "notes-section",
    "nutrition": "nutrition-section",
    "obgynepisode": "oBGyn-Episode-section",
    "obstetricshistory": "obstetrics-History-section",
    "orderedprescriptions": "ordered-Prescriptions-section",
    "pastmedicalhistory": "past-Medical-History-section",
    "pastsurgicalhistory": "pAST-SURGICAL-HISTORY-section",
    "pathologyreportnarrativenotes": "pATHOLOGY-REPORT-NARRATIVE-NOTES-section",
    "payers": "payers-section",
    "pendingorders": "pending-Orders-section",
    "physicalexam": "physicalExam-section",
    "planoftreatment": "planOfTreatment-section",
    "pleasereadprohibitiononredisclosure": "***PLEASE-READ-PROHIBITION-ON-RE-DISCLOSURE***-section",
    "pregnancy": "pregnancy-section",
    "pregnancysummary": "pregnancy-Summary-section",
    "privacymarkings": "privacy-Markings-section",
    "problem": "problem-section",
    "problems": "problems-section",
    "procedures": "procedures-section",
    "proceduresnote": "procedures-Note-section",
    "procedurespecimenstaken": "procedureSpecimensTaken-section",
    "progressnote": "progress-Note-section",
    "progressnotes": "pROGRESS-NOTES-section",
    "reasonforreferral": "reasonForReferral-section",
    "reasonforvisit": "reasonForVisit-section",
    "remotepatientmonitoring": "remote-Patient-Monitoring-section",
    "resolvedproblems": "resolved-Problems-section",
    "results": "results-section",
    "reviewofsystems": "reviewOfSystems-section",
    "securityandprivacyprohibitions": "sECURITY-AND-PRIVACY-PROHIBITIONS-section",
    "sensitiveinformationstatement": "sensitive-Information-Statement-section",
    "socialhistory": "socialHistory-section",
    "sourcecomments": "source-Comments-section",
    "summarypurpose": "summary-Purpose-section",
    "surgerydetails": "surgery-Details-section",
    "surgicalhistory": "surgical-History-section",
    "transplantepisode": "transplant-Episode-section",
    "unknown": "unknown-section",
    "visitdiagnoses": "visit-Diagnoses-section",
    "vitalsigns": "vitalSigns-section",
}
